// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProduktKatalog.Data;

#nullable disable

namespace ProduktKatalog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250919132517_AddQuantityToProducts")]
    partial class AddQuantityToProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProduktKatalog.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Maträtt",
                            Description = "Klassisk pizza med tomat och mozzarella.",
                            ImageUrl = "/images/margherita.jpg",
                            Name = "Pizza Margherita",
                            Price = 70m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 2,
                            Category = "Bakverk",
                            Description = "Svensk klassiker med kanel och kardemumma.",
                            ImageUrl = "/images/kanelbulle.jpg",
                            Name = "Kanelbulle",
                            Price = 25m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 3,
                            Category = "Bakverk",
                            Description = "Saftig chokladkaka med glasyr.",
                            ImageUrl = "/images/chokladtårta.jpg",
                            Name = "Chokladtårta",
                            Price = 40m,
                            Quantity = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
